### ISSUE TITLE
Virtual env name doesn't appear in prompt when using Starship

### ISSUE THREAD

**Issue by matorsoni** [jdholtz/pacman-venv#11]
### Description

First of all, thanks SO MUCH for this project! I was looking for something exactly like this, being a Python's `virtualenv` enthusiast.

Small issue I found: When I activate a new `pacman-venv`, the name of the virtual environment will not appear in the prompt to indicate it's active.

It still seems to be working fine, since both `pacman` and `yay` binaries are the ones from the venv.

```
❯ which yay
/home/matmat/dev/3d-gaussian-splat/pacvenv/pacman-venv-shims/yay

❯ which pacman
/home/matmat/dev/3d-gaussian-splat/pacvenv/pacman-venv-shims/pacman
```

For the record, python's `virtualenv` show up as expected in the prompt.
```
❯ python3 -m virtualenv python-venv-test
❯ source python-venv-test/bin/activate
```
![Screenshot from 2023-10-13 20-43-10](https://github.com/jdholtz/pacman-venv/assets/33296520/1017fcd3-0524-48f7-a2a6-47e3e5697bc7)

### To Reproduce

Create new virtual env `pacvenv`: `pacman-venv pacvenv`
Activate it running `source pacvenv/bin/pacman-venv-activate`
Notice that the virtual env name does not show up in the prompt (although it's active).

**Comment by jdholtz** [comment]
Glad you enjoy it! What shell are you using? Also, can you share the prompt you are using (the PS1 variable)? It probably is an issue to do with multiline prompts.

As a note, this project isn’t working very well right now (hence still being in 0.X). I haven’t had much time to work on it lately, but hopefully resolving #9 will improve the project significantly.

**Comment by matorsoni** [comment]
I'm using bash with startship prompt.
Looking forward to future updates, it has already been useful for organizing a dependency heavy repo :)

**Comment by jdholtz** [comment]
I asked how to make the custom prompt in [this discussion](https://github.com/starship/starship/discussions/5503) on Starship and came up with the following solution. Put this in your `~/.config/starship.toml` and you should be good to go (you can customize it however you want):
```bash
[custom.pacman_venv]
command = '''basename "${_PACMAN_VENV}"'''
when = '''[[ -n "${_PACMAN_VENV}" ]]'''
format = '[\[$output\] ]($style)'
```

**Comment by jdholtz** [comment]
Hey @matorsoni, any updates to my previous comment?

**Comment by matorsoni** [comment]
Oh hey sorry for the late reply. Just tested it and works like a charm!

```bash
~/dev/3d-gaussian-splat 
❯ source pacvenv/bin/pacman-venv-activate

~/dev/3d-gaussian-splat [pacvenv] 
❯ 
```
