### ISSUE TITLE
Support for non-Bash shells

### ISSUE THREAD

**Issue by noprobelm** [jdholtz/pacman-venv#4]
### Description

Hey, thanks for taking the time to make this awesome tool.

I'm unable to activate a virtual environment when using any shell other than `bash`. This is really more of a minor annoyance (I can just switch to `bash` easily enough), but I wasn't sure if this was identified by you and/or intentional for some reason.

I'm happy to provide you with any additional information you might need from my configuration.

### To Reproduce

1. Ensure a non-bash environment is activated: - `zsh`
2. Create a new virtual environment: `pacman-venv test-env`
3. Activate the virtual environment: `source test-venv/bin/pacman-venv-activate`
4. Observe stderr stream:
```
realpath: '': No such file or directory
create_path:read:2: bad option: -a
```
5. Observe stderr of `pacman` command: `zsh: no such file or directory: ./.pacman-venv-pacman` 
6. Activate bash shell: `bash`
7. Observe virtual environment is properly activated with `source test-venv/bin/pacman-venv-activate`
8. Observe successful execution of test command: `pacman -Qs` 

### Expected Behavior

A `pacman-venv` virtual environment can be successfully created regardless of the active shell environment

### Version

`pacman-venv --version`: `Pacman Virtual Environment v0.1`

**Comment by jdholtz** [comment]
Thanks for filing this. This is on the to-do list, so I will add support for other shells soon.

**Comment by jdholtz** [comment]
Hey @noprobelm, I added support for Zsh in the [zsh-support](https://github.com/jdholtz/pacman-venv/tree/zsh-support) branch. Could you test the changes to ensure they are working in your environment too? Just run `git pull && git checkout zsh-support`, recreate the virtual environment (`pacman-venv test-env --clear`), and source the script in Zsh.

**Comment by noprobelm** [comment]
Works great for me! Thank you! Keeping this open at your discretion in case you're still wanting to add support for `fish`, but my specific problem has been solved.

**Comment by jdholtz** [comment]
Awesome! I actually just finished adding support for fish this morning, so I’ll close this once I merge this branch.
